input Message {
  from: String!
  name: String!
  subject: String!
  message: String!
}

extend type Query {
  getMessageTypes: [String]!
}
extend type Mutation {
  receiveMessage(message: Message!, language: String!): Boolean!
}